const prekes = [
    {
        name: "Porai",
        price: 0,
		d1: "Vasariniai.",
		d2: "Stambūs porai išauga tik tuomet, kai daržovės auga pakankamai toli viena nuo kitos. Tankiai susodinti augalai konkuruoja dėl saulės šviesos, maisto medžiagų ir vandens. Į tą pačią vietą darže porai sodinami tik po 2-3 metų.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "porai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Mairūnai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "Kvapusis.",
		d3: "Sodinama daigais, laistomi, purenami tarpueiliai, išravimos piktžolės. Sodinant tarp augalų eilučių paliekamas 12-15 cm tarpas.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "mairunai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Bazilikai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "Raudonieji ir žalieji.",
		d3: "Gali būti auginami darže, šiltnamyje, bet taip pat ir balkone ar virtuvėje ant palangės. Geriausiai ir sparčiausiai bazilikas auga, kai oro temperatūra yra apie 25 laipsnių.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "bazilikai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Petražolės",
        price: 0,
		d1: "Vienmetis arba dvimetis prieskoninis augalas.",
		d2: "Lapinės, garbanotos, šakninės.",
		d3: "Petražolės puikiai jausis net ir šaltą vasarą, optimali augimo temperatūra - 20 laipsnių. Reikalingas retinimas, jog turėtų erdvės augti.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "petrazoles.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Salierai",
        price: 0,
		d1: "Vienmetis arba dvimetis prieskoninis augalas.",
		d2: "Lapiniai, lapkotiniai, šakniniai.",
		d3: "Salierams reikia gana daug vandens ir šilumos. Be to lapinius salierus galima auginti šalia kopūstų, pupų ir pupelių, nes atbaido vikšrus.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "salierai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Kalendros",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "Blakinė.",
		d3: "Kalendra gali būti auginama nedideliuose vazonėliuose, loveliuose, taip pat ir darže. Nereikli dirvai, mėgsta saulę.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "kalendros.jpg",
        tag: "prieskoniai"
      },	
      {
        name: "Rozmarinai",
        price: 0,
		d1: "Mūsų kraštuose vienmetis prieskoninis augalas.",
		d2: "Kvapusis.",
		d3: "Per vasarą rozmarinai laikomi balkone ar sode, atviroje ir saulėtoje vietoje, nes šešėlio nemėgsta. Nereikalauja dažno laistymo, geriau auga sausesnėje dirvoje.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "rozmarinas.png",
        tag: "prieskoniai"
      },
      {
        name: "Čiobreliai",
        price: 0,
		d1: "Daugiametis prieskoninis augalas.",
		d2: "Paprastasis.",
		d3: "Gerai auga atviroje, saulėtoje vietoje ir kalkingoje, puveningoje dirvoje. Čiobrelius vienoje vietoje tikslinga auginti 3 metus. Norint išlaikyti per žiemą, reiktų apdengti.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "ciobreliai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Gelsvės",
        price: 0,
		d1: "Daugiametis prieskoninis augalas.",
		d2: "-",
		d3: "Priežiūra minimali - geriausiai gelsvės auga puveningose priesmėlio ar vidutiniškai sunkiose priemolio giliai įdirbtose dirvose. Svarbiausia, kad augalas turėtų pakankamai vietos. Gelsvės užauga iki 2 m aukščio.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "lovage.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Raudonėliai",
        price: 0,
		d1: "Daugiametis prieskoninis augalas.",
		d2: "Paprastasis.",
		d3: "Šis augalas nereiklus dirvai, tačiau geriau auga atviroje vietoje ir derlingoje žemėje. Pavasarį išpjaunamos senos šakelės, kad raudonėlio krūmelis geriau augtų.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "oregano.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Levandos",
        price: 0,
		d1: "Daugiametis prieskoninis augalas.",
		d2: "Tikroji.",
		d3: "Tai sausų vietų augalas, mėgstantis nelabai derlingas priesmėlio arba žvyringas vietas, kuriose po lietaus neužsistovi vanduo. Taip pat geriau auga, kai gauna daugiau saulės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "levandos.jpeg",
        tag: "prieskoniai"
      },	 
      {
        name: "Melisa",
        price: 0,
		d1: "Daugiametis prieskoninis augalas.",
		d2: "Vaistinė.",
		d3: "Mėgsta saulėta vietą, drėgną dirvą. Pavėsyje melisos lapuose sumažėja eterinio aliejaus, kuris ir yra šio augalo aromato priežastis. Lauke, į žemę, melisą sodinti galima po to, kai praeina paskutinių vėlyvų šalnų grėsmė.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "melisa.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Mėta",
        price: 0,
		d1: "Daugiametis prieskoninis augalas.",
		d2: "Paprastoji, šokoladinė, braškinė.",
		d3: "Mėtos nėra reiklios augimo ir aplinkoms sąlygoms, tačiau saulėtoje vietoje jos labiau kvepės ir puikiai derės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "RŪŠIS: ",
		n3: "AUGINIMAS: ",
        img: "meta.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Pomidorai",
        price: 0,
		d1: "Ankstyvi (žemaūgiai) ir vidutinio - vėlyvumo (aukštaūgiai arba žemaūgiai)",
		d2: "Optimalios pomidorų augimui reikalingos sąlygos – šiltnamyje turi būti šilta ir sausa, bet dirva po krūmu turi būti pakankamai drėgna. Reguliariai reikia pašalinti visus senus, pageltusius ir ligotus lapaus. ",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "pomidorai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Paprika",
        price: 0,
		d1: "Raudona, geltona.",
		d2: "Paprikas vertėtų mulčiuoti, tai padidintų jų derlių. Ravint piktžoles, arti prie paprikos reikėtų jas rauti kuo atsargiau, nes šaknys yra paviršinės, negiliai išsidėsčiusios. Paprikų vaisius rekomenduojama nupjauti, o ne nuplėšti.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "paprika2.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Čili pipirai",
        price: 0,
		d1: "Raudoni.",
		d2: "Galima auginti visus metus ant palangės, terasoje, balkone. Tačiau norint auginti darže arba šiltnamyje šalia kitų saldžiųjų paprikų, reiktų palaikyti tarp jų atstumą, mat paprikos vienos kitai gali perduoti savo skonį.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "cili.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Agurkai",
        price: 0,
		d1: "Mirabelle (savidulkiai), Rodničiok, Stremski.",
		d2: "Laistyti agurkus reikia gausiai ir, jei įmanoma, sušilusiu vandeniu. Pradėjus derėti, agurkus reikia skinti bent 1-2 kartus per savaitę. Dideli agurkai išnaudoja daug maistingų medžiagų, tad sulėtėja naujų agurkų augimas, be to, skynimas skatina agurką užmegzti naujų vaisių.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "agurkai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Moliūgai",
        price: 0,
		d1: "Muskatiniai.",
		d2: "Auginant moliūgus, ant augalo paprastai paliekama po 3-4 vaisius, o norint užauginti ypač stambius vaisius – tik 1-2. Kitos vaisių užuomazgos nuskinamos, žiedams dar neišsiskleidus. Kad moliūgai užaugtų gražesni juo kelis kartus galima apversti nepersukant virkšties.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "moliugai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Cukinija",
        price: 0,
		d1: "Žalia.",
		d2: "Siekiant gausesnio derliaus ir sklandesnio cukinijų augimo, patartina į lauką cukinijas sodinti iš daigų, pasibaigus šalnoms. Cukinijos mėgstą šilumą, purią, humusingą žemę. Cukinijos vaisius reikėtų skinti gana anksti jiems dar neperaugus.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "cukinija.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Kopūstai",
        price: 0,
		d1: "Ankstyvi, vėlyvi.",
		d2: "Kopūstai labai reiklūs drėgmei. Daugiausiai vandens kopūstams reikia po daigų išsodinimo, aktyviai augant lapams ir gūžės formavimosi laikotarpiu. Ankstyvuosius kopūstus daugiau laistyti reiktų birželį, vėlyvuosius - rugpjūtį. Laistoma ryte arba vakare.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "kopustai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Kalafijorai",
        price: 0,
		d1: "Ankstyvi.",
		d2: "Norint išauginti gerą žiedinių kopūstų derlių dirvos paviršių reikia nuolat purenti, kad į dirvą galėtų patekti oras ir mažiau išgaruotų vandens. Tam tikslui yra purenami tarpueiliai, kartu sunaikinant ir pradedančias augti piktžoles. ",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "kalafijorai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Brokoliai",
        price: 0,
		d1: "Vidutinio vėlyvumo.",
		d2: "Brokoliai geriausiai auga ir dera vėsesnę, kai temperatūra yra apie 16 laipsnių, ir drėgną vasarą. Jie karščius pakenčia geriau nei žiediniai kopūstai. Rudenį suformuotos galvutės pakelia iki -5 laipsnių atšalimus.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "brokoliai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Burokėliai",
        price: 0,
		d1: "Apvalūs.",
		d2: "Burokėliai yra nereiklūs, gerai auga lengvoje ar vidutinio sunkumo priemolio ar priesmėlio dirvoje. Jų reguliariai laistyti nebūtina, patartina purenti, neleisti užgožti piktžolėms.",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "burokeliai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Baklažanai",
        price: 0,
		d1: "Pailgi.",
		d2: "Baklažanai yra jautrūs drėgmės pertekliui. Šias daržoves reikia laistyti gausiai, bet vanduo neturi užsistovėti. Laistydami nedrėkinkite lapų. Vanduo turi būti šiltas. Baklažanai smarkiai šakojasi - šį procesą reikia kontroliuoti. Reiktų palikti ant augalo 3-4 ūglius, o kitus pašalinti. ",
		d3: "",
		n1: "RŪŠIS: ",
		n2: "AUGINIMAS: ",
		n3: "",
        img: "eggplant2.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Žemuogė Rugen",
        price: 0,
		d1: "Remontantinė, visasezonė veislė.",
		d2: "Ypač aromatingos ir stambios.",
		d3: "Žemuogės yra gan neįnoringi augalai, galintys augti įvairiomis sąlygomis: saulėkaitoje, daliniame pavėsyje. Tačiau dirva turi būti pailsėjusi nuo sodo žemuogių bent kelis metus.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "SODINIMAS: ",
        img: "rugen.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Honeoye",
        price: 0,
		d1: "Ankstyva veislė.",
		d2: "Odelė ryškiai raudona iki tamsiai raudonos. Minkštimas šviesiai raudonas, sultingas, gero skonio.",
		d3: "Šalčiui, uogų puvimui, lapų ligoms, tačiau reiktų vengti sodinti ten, kur jau augo kitos braškės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "honoja.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Polka",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos stambios, vienodos formos, intensyviai raudonos spalvos.",
		d3: "Lapų ligai miltligei, puviniui, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "polka.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Elkat",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos didelės, tvirtos konsistencijos, plataus kūgio formos.",
		d3: "Šaknų sistemos ligoms, lapų ligoms šviesmargei, miltligei, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "elkat.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Senga Sengana",
        price: 0,
		d1: "Vidutinio vėlyvumo.",
		d2: "Uogos stambios ir vidutinio stambumo, širdiškai apvalios, tamsiai rusvai raudonos.",
		d3: "Braškiniam nematodui, šaknų sistemos ligoms, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "sengana.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Dukat",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos didelės ir labai didelės, apvalios arba plačiai kūginės. Odelė ryškiai raudona.",
		d3: "Lapų ligai miltligei, šaknų sistemos ligoms, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "dukat.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Grandarosa",
        price: 0,
		d1: "Ankstyva veislė.",
		d2: "Šviesiai rožinės spalvos, tvirtos konsistencijos.",
		d3: "Lapų ligoms šviesmargei, miltligei, šalčiui. ",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "grandarosa.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė San Andreas",
        price: 0,
		d1: "Remontantinė, visasezonė veislė.",
		d2: "Tvirtos ir itin saldžios.",
		d3: "puviniui, lapų ligoms, tačiau turėtų būti saugoma nuo didesnio šalčio.",
		n1: "ŽIEDAI: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "san-andreas.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Arbatinės (10 veislių)",
        price: 0,
		d1: "Stambūs (10-15 cm skersmens), pavieniai.",
		d2: "50 cm - 1,3 m.",
		d3: "Du kartus per sezoną.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS:",
		n3: "ŽYDĖJIMAS: ",
        img: "arbatine.jpg",
        tag: "Rožių krūmai"
      },
      {
        name: "Krūminės (5 veislės)",
        price: 0,
		d1: "Žydi ne pavieniais žiedais, o kekėmis.",
		d2: "1 - 1,5 m.",
		d3: "Visą vasarą.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "ŽYDĖJIMAS: ",
        img: "krumine.jpg",
        tag: "Rožių krūmai"
      },
      {
        name: "Vijoklinės (3 veislės)",
        price: 0,
		d1: "Smulkūs arba stambūs, išsidėstę per visą stiebą.",
		d2: "1,5 - 2,5 m.",
		d3: "Žiedai pražysta skirtingu metu, tad žydi visą vasarą.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "ŽYDĖJIMAS: ",
        img: "vijokline.jpg",
        tag: "Rožių krūmai"
      },
      {
        name: "Floribundinės (10 veislių)",
        price: 0,
		d1: "Žiedynai itin gausūs, kiekvienas po 17-40 žiedų.",
		d2: "iki 1,2 m.",
		d3: "Visą sezoną.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "ŽYDĖJIMAS: ",
        img: "floribundine.jpg",
        tag: "Rožių krūmai"
      },
      {
        name: "Medutis",
        price: 0,
		d1: "Itin kvapnūs, balti.",
		d2: "Žali.",
		d3: "Medutis geriausiai auga saulėtoje vietoje. Per tankiai susodinti augalai silpnai žydi. Šias gėles reikėtų sodinti ten, kur jų nestelbtų kiti augalai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "medutis.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Našlaitė",
        price: 0,
		d1: "Geltoni su juodu viduriuku.",
		d2: "Žali.",
		d3: "Itin derlinga žemė nėra būtina. Kadangi tokioms gėlėms kaip našlaitės nereikia didelio žemių kiekio, jas galima iš karto pasodinti į gėlių vazonus. ",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "naslaite.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Margenis",
        price: 0,
		d1: "Nežydi.",
		d2: "Tamsiai raudoni su juodais apvadėliais.",
		d3: "Nors tai gana ištvermingas augalas, kaip ir visiems margalapiams jam reikia ryškios šviesos, kad lapų spalvos pernelyg neišbluktų, mėgsta drėgmę.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "margenis.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Lobelija",
        price: 0,
		d1: "Smulkūs, mėlyni, itin gausūs.",
		d2: "Tamsiai žali.",
		d3: "Karštomis ir sausomis dienomis lobelijas, ypač auginamas vazonuose, reikėtų laistyti du kartus per dieną, ryte ir vakare. Esant nepakankamam drėgmės kiekiui, lobelija gali nebežydėti.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "lobelija.jfif",
        tag: "vasarinės gėlės"
      },
      {
        name: "Smulkiažiedė begonija",
        price: 0,
		d1: "Smulkūs, raudoni, balti.",
		d2: "Žali arba tamsiai raudoni, stori ir vaškuoti.",
		d3: "Mėgsta šilumą ir drėgmę, tačiau galėtų išgyventi trumpą sausrą. Gali augti daliniame šešėlyje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "begonija.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Salvija (Šalavijas)",
        price: 0,
		d1: "Raudoni.",
		d2: "Žali.",
		d3: "Šalavijai nėra itin reiklūs. Gražiausiai atrodo susodinti didesniais plotais. Žydėjimo pabaigoje reiktų nupjauti iki pat žemės, taip jie greičiau atželia ir rudenį pražysta pakartotinai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "salvija.jfif",
        tag: "vasarinės gėlės"
      },
      {
        name: "Tagetės",
        price: 0,
		d1: "Geltoni, oranžiniai, tamsiai vyšniniai ir kiti.",
		d2: "Žali, karpyti.",
		d3: "Tai mėgstantys šilumą ir nepakenčiantys šalnų augalai, itin atsparūs sausrai. Tagetes patariama auginti atviroje, saulėtoje vietoje, nors jos gali augti ir prietemoje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "serentis.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Žydrūnai",
        price: 0,
		d1: "Mėlyni.",
		d2: "Žali.",
		d3: "Ši gėlė mėgsta sunkesnę, kalkingą dirvą, saulėtą arba pusiau saulėtą vietą. Į pastovią augimo vietą sodinamas praėjus šalnų pavojui.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "zydrunas.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Palergonija",
        price: 0,
		d1: "Raudoni, oranžiniai.",
		d2: "Šviesiai arba tamsiai žali.",
		d3: "Krūminės pelargonijos yra reiklios šviesai ir drėgmei. Šiam augalui reikalinga derlinga dirva.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "pelargonija.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Verbena",
        price: 0,
		d1: "Raudoni.",
		d2: "Žali, smulkūs.",
		d3: "Krūminė verbena sodinama lysvelėse, palangių bei balkonų dėžutėse. Dirvožemiui verbena nereikli, bet ji mėgsta saulėtą, atvirą vietą. Atspari mažoms šalnoms. ",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "verbena.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Jurginėliai",
        price: 0,
		d1: "Vyšniniai.",
		d2: "Žali.",
		d3: "Jie mėgsta šilumą ir saulę, todėl juos reikia sodinti saulėtose ir nuo šiaurės vėjų apsaugotose vietose. Nereiklūs priežiūrai, tačiau genėjimas užtikrintų didesnius žiedus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "jurginai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Šlamutis",
        price: 0,
		d1: "Nežydi.",
		d2: "Dekoratyvūs, pilki, smulkūs.",
		d3: "Atsparūs nedidelėms šalnoms, auginimui reikia daugiau vietos, galima formuoti šaligatvio bortelius, taip pat kiliminius gėlynus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "slamutis.png",
        tag: "vasarinės gėlės"
      },
      {
        name: "Bakopa",
        price: 0,
		d1: "Balti, žydri, rožiniai, smulkūs.",
		d2: "Žali, smulkūs.",
		d3: "Bakopos nereiklios, itin atsparios nepalankioms augimo sąlygoms. Nepraranda savo grožio net po užsitęsusio lietaus. Bakopos numeta pradėjusius vysti žiedus, todėl augalas visada atrodo gražiai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "bakopa.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Verbena",
        price: 0,
		d1: "Raudoni, rožiniai.",
		d2: "Žali.",
		d3: "Reiktų laiku pašalinti peržydėjusius žiedynus - žydės gausiau ir gražiau atrodys. Taip pat rekomenduojama karts nuo karto tręšti o  lietingu oru profilaktiškai nupurkšti nuo miltligės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "SvyrantiVerbena.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Begonija",
        price: 0,
		d1: "Oranžiniai.",
		d2: "Žaliai raudoni.",
		d3: "Mėgsta lengvą, derlingą dirvą, patinka saulėta vieta, nors neblogai auga ir pavėsyje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "begonija-svyranti.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Surfinija",
        price: 0,
		d1: "Balti, tamsiai mėlyni, raudoni, rožiniai ir kiti.",
		d2: "Žali.",
		d3: "Ji gali žydėti visą vasaros sezoną. Tam būtinas gilus vazonas, reguliarus laistymas bei tręšimas ir nužydėjusių žiedų pašalinimas.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Palergonija",
        price: 0,
		d1: "Raudoni.",
		d2: "Tamsiai žali.",
		d3: "Skirtos auginti pakabinamuose loviuose arba aukštuose pastatomuose konteineriuose. Ši gėlė prieš šalnas parnešta į namus gali sėkmingai peržiemoti.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "SvyrantiPalergonija.jpg", 
        tag: "svyrančios gėlės"
      },
      {
        name: "Kalibrachoja",
        price: 0,
		d1: "Mėlyni, raudoni, balti, geltoni ir kiti.",
		d2: "Žali.",
		d3: "Kitaip vadinama kaip smulkiažiedė surfinija, tad jos priežiūra praktiškai identiška surfinijai. Žiedai nebijo stipraus lietaus ir vėjo.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalibrachoja.jpg",
        tag: "svyrančios gėlės"
      } 
];

    
const tavar = [
  {
      name: "Porai",
      price: 0,
      description: "Vasariniai",
      img: "daigai.jpg",
      tag: "prieskoniai"
    },
    {
      name: "Pomidorai",
      price: 0,
      description: "ankstyvi(žemaūgiai), vidutinio - vėlyvumo (Aukštaūgiai, žemaūgiai)",
      img: "basil.jfif",
      tag: "daržovės"
    },
    {
      name: "Žemuogė Rugen",
      price: 0,
      description: "",
      img: "braske.jfif",
      tag: "Daržovės"
    },
    {
      name: "Arbatinės",
      price: 0,
      description: "sonoo",
      img: "rose2.jpg",
      tag: "rožės"
    },
    {
      name: "Medutis",
      price: 0,
      description: "",
      img: "kalvarijai.jpg",
      tag: "vasarinės gėlės"
    },
    {
      name: "Bakopa",
      price: 0,
      description: "sonoo",
      img: "surfinija.jpg",
      tag: "svyrančios"
    }
];
