const prekes = [
    {
        name: "Porai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "porai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Mairūnai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "viežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "mairunai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Bazilikai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "bazilikai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Petražolės",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Tik gerai apšviestoje vietoje (net šešėlis nuo medžio trukdo augalams žydėti ir megzti uogas. Dirva turi būti pailsėjusi.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "petrazoles.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Salierai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "salierai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Kalendros",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "kalendros.jpg",
        tag: "prieskoniai"
      },	
      {
        name: "Rozmarinai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "rozmarinai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Čiobreliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "ciobreliai.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Gelsvės",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "lovage.jfif",
        tag: "prieskoniai"
      },
      {
        name: "Raudonėliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "oregano.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Levandos",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "levandos.jpeg",
        tag: "prieskoniai"
      },	 
      {
        name: "Melisa",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "melisa.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Mėta",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "meta.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Pomidorai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "pomidorai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Paprika",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "paprika2.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Čili pipirai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "cili.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Agurkai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "agurkai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Moliūgai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "moliugai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Cukinija",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "cukinija.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Kopūstai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "kopustai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Kalafijorai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "kalafijorai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Brokoliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "brokoliai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Burokėliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "burokeliai.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Baklažanai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "eggplant2.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Žemuogė Rugen",
        price: 0,
		d1: "Remontantinė, visasezonė veislė.",
		d2: "Ypač aromatingos ir stambios.",
		d3: "Žemuogės yra gan neįnoringi augalai, galintys augti įvairiomis sąlygomis: saulėkaitoje, daliniame pavėsyje. Tačiau dirva turi būti pailsėjusi nuo sodo žemuogių bent kelis metus.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "SODINIMAS: ",
        img: "rugen.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Honeoye",
        price: 0,
		d1: "Ankstyva veislė.",
		d2: "Odelė ryškiai raudona iki tamsiai raudonos. Minkštimas šviesiai raudonas, sultingas, gero skonio.",
		d3: "Šalčiui, uogų puvimui, lapų ligoms, tačiau reiktų vengti sodinti ten, kur jau augo kitos braškės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "honoja.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Polka",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos stambios, vienodos formos, intensyviai raudonos spalvos.",
		d3: "Lapų ligai miltligei, puviniui, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "polka.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Elkat",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos didelės, tvirtos konsistencijos, plataus kūgio formos.",
		d3: "Šaknų sistemos ligoms, lapų ligoms šviesmargei, miltligei, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "elkat.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Senga Sengana",
        price: 0,
		d1: "Vidutinio vėlyvumo.",
		d2: "Uogos stambios ir vidutinio stambumo, širdiškai apvalios, tamsiai rusvai raudonos.",
		d3: "Braškiniam nematodui, šaknų sistemos ligoms, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "sengana.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Dukat",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos didelės ir labai didelės, apvalios arba plačiai kūginės. Odelė ryškiai raudona.",
		d3: "Lapų ligai miltligei, šaknų sistemos ligoms, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "dukat.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Grandarosa",
        price: 0,
		d1: "Ankstyva veislė.",
		d2: "Šviesiai rožinės spalvos, tvirtos konsistencijos.",
		d3: "Lapų ligoms šviesmargei, miltligei, šalčiui. ",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "grandarosa.jpg",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė San Andreas",
        price: 0,
		d1: "Remontantinė, visasezonė veislė.",
		d2: "Tvirtos ir itin saldžios.",
		d3: "puviniui, lapų ligoms, tačiau turėtų būti saugoma nuo didesnio šalčio.",
		n1: "ŽIEDAI: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "san-andreas.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Arbatinės (10 veislių)",
        price: 0,
		d1: "Stambūs (10-15 cm skersmens), pavieniai.",
		d2: "50 cm - 1,3 m.",
		d3: "Du kartus per sezoną.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS:",
		n3: "ŽYDĖJIMAS: ",
        img: "arbatine.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Krūminės (5 veislių)",
        price: 0,
		d1: "Žydi ne pavieniais žiedais, o kekėmis.",
		d2: "1 - 1,5 m.",
		d3: "Visą vasarą.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "ŽYDĖJIMAS: ",
        img: "krumine.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Vijoklinės (2 veislės)",
        price: 0,
		d1: "Smulkūs arba stambūs, išsidėstę per visą stiebą.",
		d2: "1,5 - 2,5 m.",
		d3: "Žiedai pražysta skirtingu metu, tad žydi visą vasarą.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "ŽYDĖJIMAS: ",
        img: "vijokline.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Floribundinės (10 veislių)",
        price: 0,
		d1: "Žiedynai itin gausūs, kiekvienas po 17-40 žiedų.",
		d2: "iki 1,2 m.",
		d3: "Visą sezoną.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "ŽYDĖJIMAS: ",
        img: "floribundine.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Medutis",
        price: 0,
		d1: "Itin kvapnūs, balti.",
		d2: "Žali.",
		d3: "Medutis geriausiai auga saulėtoje vietoje. Per tankiai susodinti augalai silpnai žydi. Šias gėles reikėtų sodinti ten, kur jų nestelbtų kiti augalai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "medutis.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Našlaitė",
        price: 0,
		d1: "Geltoni su juodu viduriuku.",
		d2: "Žali.",
		d3: "Itin derlinga žemė nėra būtina. Kadangi tokioms gėlėms kaip našlaitės nereikia didelio žemių kiekio, jas galima iš karto pasodinti į gėlių vazonus. ",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "naslaite.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Margenis",
        price: 0,
		d1: "Nežydi.",
		d2: "Tamsiai raudoni su juodais apvadėliais.",
		d3: "Nors tai gana ištvermingas augalas, kaip ir visiems margalapiams jam reikia ryškios šviesos, kad lapų spalvos pernelyg neišbluktų, mėgsta drėgmę.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "margenis.jfif",
        tag: "vasarinės gėlės"
      },
      {
        name: "Lobelija",
        price: 0,
		d1: "Smulkūs, mėlyni, itin gausūs.",
		d2: "Tamsiai žali.",
		d3: "Karštomis ir sausomis dienomis lobelijas, ypač auginamas vazonuose, reikėtų laistyti du kartus per dieną, ryte ir vakare. Esant nepakankamam drėgmės kiekiui, lobelija gali nebežydėti.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "lobelija.jfif",
        tag: "vasarinės gėlės"
      },
      {
        name: "Smulkiažiedė begonija",
        price: 0,
		d1: "Smulkūs, raudoni, balti.",
		d2: "Žali arba tamsiai raudoni, stori ir vaškuoti.",
		d3: "Mėgsta šilumą ir drėgmę, tačiau galėtų išgyventi trumpą sausrą. Gali augti daliniame šešėlyje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "begonija.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Salvija (Šalavijas)",
        price: 0,
		d1: "Raudoni.",
		d2: "Žali.",
		d3: "Šalavijai nėra itin reiklūs. Gražiausiai atrodo susodinti didesniais plotais. Žydėjimo pabaigoje reiktų nupjauti iki pat žemės, taip jie greičiau atželia ir rudenį pražysta pakartotinai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "salvija.jfif",
        tag: "vasarinės gėlės"
      },
      {
        name: "Tagetės",
        price: 0,
		d1: "Geltoni, oranžiniai, tamsiai vyšniniai ir kiti.",
		d2: "Žali, karpyti.",
		d3: "Tai mėgstantys šilumą ir nepakenčiantys šalnų augalai, itin atsparūs sausrai. Tagetes patariama auginti atviroje, saulėtoje vietoje, nors jos gali augti ir prietemoje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "serentis.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Žydrūnai",
        price: 0,
		d1: "Mėlyni.",
		d2: "Žali.",
		d3: "Ši gėlė mėgsta sunkesnę, kalkingą dirvą, saulėtą arba pusiau saulėtą vietą. Į pastovią augimo vietą sodinamas praėjus šalnų pavojui.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "zydrunas.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Palergonija",
        price: 0,
		d1: "Raudoni, oranžiniai.",
		d2: "Šviesiai arba tamsiai žali.",
		d3: "Krūminės pelargonijos yra reiklios šviesai ir drėgmei. Šiam augalui reikalinga derlinga dirva.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "pelargonija.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Verbena",
        price: 0,
		d1: "Raudoni.",
		d2: "Žali, smulkūs.",
		d3: "Krūminė verbena sodinama lysvelėse, palangių bei balkonų dėžutėse. Dirvožemiui verbena nereikli, bet ji mėgsta saulėtą, atvirą vietą. Atspari mažoms šalnoms. ",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "verbena.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Jurginėliai",
        price: 0,
		d1: "Vyšniniai.",
		d2: "Žali.",
		d3: "Jie mėgsta šilumą ir saulę, todėl juos reikia sodinti saulėtose ir nuo šiaurės vėjų apsaugotose vietose. Nereiklūs priežiūrai, tačiau genėjimas užtikrintų didesnius žiedus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "jurginai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Šlamutis",
        price: 0,
		d1: "Nežydi.",
		d2: "Dekoratyvūs, pilki, smulkūs.",
		d3: "Atsparūs nedidelėms šalnoms, auginimui reikia daugiau vietos, galima formuoti šaligatvio bortelius, taip pat kiliminius gėlynus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "slamutis.png",
        tag: "vasarinės gėlės"
      },
      {
        name: "Bakopa",
        price: 0,
		d1: "Balti, žydri, rožiniai, smulkūs.",
		d2: "Žali, smulkūs.",
		d3: "Bakopos nereiklios, itin atsparios nepalankioms augimo sąlygoms. Nepraranda savo grožio net po užsitęsusio lietaus. Bakopos numeta pradėjusius vysti žiedus, todėl augalas visada atrodo gražiai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "bakopa.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Verbena",
        price: 0,
		d1: "Raudoni, rožiniai.",
		d2: "Žali.",
		d3: "Reiktų laiku pašalinti peržydėjusius žiedynus - žydės gausiau ir gražiau atrodys. Taip pat rekomenduojama karts nuo karto tręšti o  lietingu oru profilaktiškai nupurkšti nuo miltligės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "verbena.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Begonija",
        price: 0,
		d1: "Oranžiniai.",
		d2: "Žaliai raudoni.",
		d3: "Mėgsta lengvą, derlingą dirvą, patinka saulėta vieta, nors neblogai auga ir pavėsyje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "begonija-svyranti.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Surfinija",
        price: 0,
		d1: "Balti, tamsiai mėlyni, raudoni, rožiniai ir kiti.",
		d2: "Žali.",
		d3: "Ji gali žydėti visą vasaros sezoną. Tam būtinas gilus vazonas, reguliarus laistymas bei tręšimas ir nužydėjusių žiedų pašalinimas.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Palergonija",
        price: 0,
		d1: "Raudoni.",
		d2: "Tamsiai žali.",
		d3: "Skirtos auginti pakabinamuose loviuose arba aukštuose pastatomuose konteineriuose. Ši gėlė prieš šalnas parnešta į namus gali sėkmingai peržiemoti.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "pelargonija.jpg", 
        tag: "svyrančios gėlės"
      },
      {
        name: "Kalibrachoja",
        price: 0,
		d1: "Mėlyni, raudoni, balti, geltoni ir kiti.",
		d2: "Žali.",
		d3: "Kitaip vadinama kaip smulkiažiedė surfinija, tad jos priežiūra praktiškai identiška surfinijai. Žiedai nebijo stipraus lietaus ir vėjo.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalibrachoja.jpg",
        tag: "svyrančios gėlės"
      } 
];

    
const tavar = [
  {
      name: "Porai",
      price: 0,
      description: "Vasariniai",
      img: "daigai.jpg",
      tag: "prieskoniai"
    },
    {
      name: "Pomidorai",
      price: 0,
      description: "ankstyvi(žemaūgiai), vidutinio - vėlyvumo (Aukštaūgiai, žemaūgiai)",
      img: "basil.jfif",
      tag: "daržovės"
    },
    {
      name: "Žemuogė Rugen",
      price: 0,
      description: "",
      img: "braske.jfif",
      tag: "Daržovės"
    },
    {
      name: "Arbatinės",
      price: 0,
      description: "sonoo",
      img: "rose2.jpg",
      tag: "rožės"
    },
    {
      name: "Medutis",
      price: 0,
      description: "",
      img: "kalvarijai.jpg",
      tag: "vasarinės gėlės"
    },
    {
      name: "Bakopa",
      price: 0,
      description: "sonoo",
      img: "surfinija.jpg",
      tag: "svyrančios"
    }
];
