const prekes = [
    {
        name: "Porai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "Daržovių daigai"
      },
      {
        name: "Mairūnai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "viežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Bazilikai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Petražolės",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Tik gerai apšviestoje vietoje (net šešėlis nuo medžio trukdo augalams žydėti ir megzti uogas. Dirva turi būti pailsėjusi.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Salierai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Kalendros",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },	
      {
        name: "Rozmarinai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Čiobreliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Gelsvės",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Raudonėliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Levandos",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },	 
      {
        name: "Melisa",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Mėta",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "daigai.jpg",
        tag: "prieskoniai"
      },
      {
        name: "Pomidorai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Paprika",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Čili pipirai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Agurkai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Moliūgai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Cukinija",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Kopūstai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Kalafijorai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Brokoliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Burokėliai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Baklažanai",
        price: 0,
		d1: "Vienmetis prieskoninis augalas.",
		d2: "šviežius ar džiovintus. Tinka salotoms, mėsos, varškės ar daržovių patiekalams gardinti.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "VARTOJIMAS: ",
		n3: "SODINIMAS: ",
        img: "basil.jfif",
        tag: "Daržovių daigai"
      },
      {
        name: "Žemuogė Rugen",
        price: 0,
		d1: "Remontantinė, visasezonė veislė.",
		d2: "Ypač aromatingos ir stambios.",
		d3: "Gerai apšviestoje vietoje (net šešėlis nuo medžio trukdo augalams žydėti ir megzti uogas). Dirva turi būti pailsėjusi nuo sodo žemuogių bent kelis metus.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "SODINIMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Honeoye",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Odelė ryškiai raudona iki tamsiai raudonos. Minkštimas šviesiai raudonas, sultingas, gero skonio.",
		d3: "Šalčiui, uogų puvimui, lapų ligoms, tačiau reiktų vengti sodinti ten, kur jau augo kitos braškės.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Polka",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos stambios, vienodos formos, intensyviai raudonos spalvos.",
		d3: "Lapų ligai miltligei, puviniui, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Elkat",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos didelės, tvirtos konsistencijos, plataus kūgio formos.",
		d3: "Šaknų sistemos ligoms, lapų ligoms šviesmargei, miltligei, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Senga Sengana",
        price: 0,
		d1: "Vėlyva veislė.",
		d2: "Uogos stambios ir vidutinio stambumo, širdiškai apvalios, tamsiai rusvai raudonos.",
		d3: "Braškiniam nematodui, šaknų sistemos ligoms, šalčiui, tačiau reiktų saugoti nuo miltligės, puvinio.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Dukat",
        price: 0,
		d1: "Vidutinio ankstyvumo.",
		d2: "Uogos didelės ir labai didelės, apvalios arba plačiai kūginės. Odelė ryškiai raudona.",
		d3: "Lapų ligai miltligei, šaknų sistemos ligoms, šalčiui.",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė Grandarosa",
        price: 0,
		d1: "Ankstyva veislė.",
		d2: "Šviesiai rožinės spalvos, tvirtos konsistencijos.",
		d3: "Lapų ligoms šviesmargei, miltligei, šalčiui. ",
		n1: "SEZONIŠKUMAS: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Braškė San Andreas",
        price: 0,
		d1: "Remontantinė, visasezonė veislė.",
		d2: "Tvirtos ir itin saldžios vasaros metu, mažiau saldžios sezono pabaigoje.",
		d3: "puviniui, lapų ligoms, tačiau turėtų būti saugoma nuo didesnio šalčio.",
		n1: "ŽIEDAI: ",
		n2: "UOGOS: ",
		n3: "ATSPARUMAS: ",
        img: "braske.jfif",
        tag: "Braškės ir žemuogės"
      },
      {
        name: "Arbatinės",
        price: 0,
		d1: "Stambūs (10-15 cm skersmens), pavieniai.",
		d2: "30 cm - 1 m.",
		d3: "Nestambūs, glaustomis šakomis arba šiek tiek išsikeroję.",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS:",
		n3: "KRŪMAS: ",
        img: "rose2.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Krūminės",
        price: 0,
		d1: "Po 3 - 15 žiedų.",
		d2: "1 - 3 m.",
		d3: "Stambūs, puošnūs, gebantys augti be atramos.",
		n1: "ŽIEDYNAI: ",
		n2: "AUKŠTIS: ",
		n3: "KRŪMAS: ",
        img: "rose2.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Vijoklinės",
        price: 0,
		d1: "Smulkūs, 2 — 3 cm skersmens, išsidėstę per visą stiebą, dekoratyvūs iki 15 — 20 dienų.",
		d2: "Iki kelių metrų.",
		d3: "Statmenai augti negali, turi driektis per atramas (tvoras, pastatus).",
		n1: "ŽIEDAI: ",
		n2: "AUKŠTIS: ",
		n3: "KRŪMAS: ",
        img: "rose2.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Floribundinės",
        price: 0,
		d1: "Itin gausūs, kiekvienas po 17-40 žiedų.",
		d2: "iki 1 m.",
		d3: "Nestambūs, kompaktiški.",
		n1: "ŽIEDYNAI: ",
		n2: "AUKŠTIS: ",
		n3: "KRŪMAS: ",
        img: "rose2.jpg",
        tag: "Rožių sodinukai"
      },
      {
        name: "Lobuliarija (Medutis)",
        price: 0,
		d1: "Itin kvapnūs, balti.",
		d2: "Žali.",
		d3: "Lobuliarijos geriausiai auga saulėtoje vietoje. Per tankiai susodinti augalai silpnai žydi. Lobuliarijas reikėtų sodinti ten, kur jų nestelbtų kiti augalai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Našlaitė",
        price: 0,
		d1: "Geltoni, geltoni su juodu viduriuku, balti, mėlyni.",
		d2: "Žali.",
		d3: "Itin derlinga žemė nėra būtina. Kadangi tokioms gėlėms kaip našlaitės nereikia didelio žemių kiekio, jas galima iš karto pasodinti į gėlių vazonus. ",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Margenis",
        price: 0,
		d1: "Nežydi.",
		d2: "Tamsiai raudoni su juodais apvadėliais.",
		d3: "Nors tai gana ištvermingas augalas, kaip ir visiems margalapiams jam reikia ryškios šviesos, kad lapų spalvos pernelyg neišbluktų. Mėgsta drėgmę, o stiprus vėjas gali numesti lapus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Aukštaūgiai astrai",
        price: 0,
		d1: "Įvairių spalvų.",
		d2: "Tamsiai žali.",
		d3: "gan ištvermingas augalas, kaip ir visiems margalapiams jam reikia ryškios šviesos, kad lapų spalvos pernelyg neišbluktų. Mėgsta drėgmę, o dėl stipraus vėjo gali nukristi lapai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Lobelija",
        price: 0,
		d1: "Tamsiai žali.",
		d2: "Smulkūs, mėlyni, itin gausūs.",
		d3: "Karštomis ir sausomis dienomis lobelijas, ypač auginamas vazonuose, reikėtų laistyti du kartus per dieną, ryte ir vakare. Esant nepakankamam drėgmės kiekiui, lobelija gali nebežydėti..",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Begonija (ledinukai)",
        price: 0,
		d1: "Smulkūs, raudoni, Balti.",
		d2: "Stori ir vaškuoti, žali arba tamsiai raudoni.",
		d3: "Mėgsta šilumą ir drėgmę, tačiau galėtų išgyventi trumpą sausrą. Geriau auga daliniame šešėlyje (mažiau tįsta ūgliai).",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Salvija (Šalavijas)",
        price: 0,
		d1: "Raudoni.",
		d2: "Žali.",
		d3: "Šalavijai nėra itin reiklūs. Gražiausiai atrodo susodinti didesniais plotais. Žydėjimo pabaigoje reiktų nupjauti iki pat žemės, taip jie greičiau atželia ir rudenį pražysta pakartotinai.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Tagetės (serenčiai)",
        price: 0,
		d1: "Geltonos, oranžinės.",
		d2: "Žali, karpyti.",
		d3: "tai mėgstantys šilumą ir nepakenčiantys šalnų augalai. Serenčius patariama auginti atviroje, saulėtoje vietoje, nors jie gali augti ir prietemoje.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Žydrūnai",
        price: 0,
		d1: "Mėlyni.",
		d2: "Žali.",
		d3: "Ši gėlė mėgsta sunkesnę, kalkingą dirvą, saulėtą arba pusiau saulėtą vietą. Į pastovią augimo vietą sodinamas praėjus šalnų pavojui.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Palergonija",
        price: 0,
		d1: "Raudoni, oranžiniai.",
		d2: "Šviesiai arba tamsiai žali.",
		d3: "Pelargonijos yra reiklios šviesai ir drėgmei. Šiam augalui reikalinga derlinga dirva, prastai auga arba nuvysta molio dirvoje, kur negiliai yra gruntiniai vandenys.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Verbena",
        price: 0,
		d1: "Balti.",
		d2: "Žali, smulkūs.",
		d3: "Krūminė verbena sodinama lysvelėse, palangių bei balkonų dėžutėse. Dirvožemiui verbena nereikli, bet ji mėgsta saulėtą, atvirą vietą. Atspari mažoms šalnoms. ",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Jurginėliai",
        price: 0,
		d1: "Vyšniniai.",
		d2: "Žali.",
		d3: "Jie mėgsta šilumą ir saulę, todėl juos reikia sodinti saulėtose ir nuo šiaurės vėjų apsaugotose vietose. Nereiklūs priežiūrai, tačiau genėjimas užtikrintų didesnius žiedus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Žilasis šlamutis",
        price: 0,
		d1: "Nežydi.",
		d2: "Dekoratyvūs, pilki, smulkūs.",
		d3: "Bijo šalnų, auginimui reikia daugiau vietos, galima formuoti - šaligatvio bortelius, taip pat kiliminius gėlynus.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "kalvarijai.jpg",
        tag: "vasarinės gėlės"
      },
      {
        name: "Bakopa",
        price: 0,
		d1: "Balti, smulkūs.",
		d2: "Šviesiai žali, smulkūs.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Verbena",
        price: 0,
		d1: "Raudoni.",
		d2: "Žali.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Begonija",
        price: 0,
		d1: "Raudoni.",
		d2: "Tamsiai raudoni.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Surfinija",
        price: 0,
		d1: "Stambūs balti, tamsiai mėlyni, raudoni, rožiniai.",
		d2: "Žali.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      },
      {
        name: "Palergonija",
        price: 0,
		d1: "Raudoni, oranžiniai.",
		d2: "Tamsiai raudoni.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
		img: "surfinija.jpg", 
        tag: "svyrančios gėlės"
      },
      {
        name: "Kalibrachoja",
        price: 0,
		d1: "Smulkūs mėlyni, raudoni, balti.",
		d2: "Žali.",
		d3: "Kas 20–30 cm. Gerai auga saulėtoje ir šiltoje, nuo vėjo apsaugotoje vietoje. Galima auginti virtuvėje ant palangės.",
		n1: "ŽIEDAI: ",
		n2: "LAPAI: ",
		n3: "PRIEŽIŪRA: ",
        img: "surfinija.jpg",
        tag: "svyrančios gėlės"
      } 
];

    
const tavar = [
  {
      name: "Porai",
      price: 0,
      description: "Vasariniai",
      img: "daigai.jpg",
      tag: "prieskoniai"
    },
    {
      name: "Pomidorai",
      price: 0,
      description: "ankstyvi(žemaūgiai), vidutinio - vėlyvumo (Aukštaūgiai, žemaūgiai)",
      img: "basil.jfif",
      tag: "daržovės"
    },
    {
      name: "Žemuogė Rugen",
      price: 0,
      description: "",
      img: "braske.jfif",
      tag: "Daržovės"
    },
    {
      name: "Arbatinės",
      price: 0,
      description: "sonoo",
      img: "rose2.jpg",
      tag: "rožės"
    },
    {
      name: "Medutis",
      price: 0,
      description: "",
      img: "kalvarijai.jpg",
      tag: "vasarinės gėlės"
    },
    {
      name: "Bakopa",
      price: 0,
      description: "sonoo",
      img: "surfinija.jpg",
      tag: "svyrančios"
    }
];
